<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JioFiber</name>
   <tag></tag>
   <elementGuidId>e11c802b-7391-4561-a673-2a352023296a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;gotoURLGeneric('','No');trackGenericGA('Click','JioFiber','New top header','revamped_jiocom')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f19acbe-862a-4486-a2f8-d2778cc616ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/fiber.html</value>
      <webElementGuid>e9fe4486-c6a2-4afe-8389-b4b5da80e1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cust-url</name>
      <type>Main</type>
      <value>/fiber.html</value>
      <webElementGuid>d9d69d16-3ed8-491b-a1dd-b3301ff9c0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gotoURLGeneric('','No');trackGenericGA('Click','JioFiber','New top header','revamped_jiocom')</value>
      <webElementGuid>2831104c-0874-4664-8e29-6218f6a67c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>j-link j-text-body-s-bold  is-text header_item-links_link  </value>
      <webElementGuid>d1111549-223b-4c08-b34a-d72e951a4c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>JioFiber</value>
      <webElementGuid>2cbe088c-0e52-493c-ba96-b5f3675d8816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>28c719af-9979-4235-8094-818e739c4bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>69d66595-16ec-4b2c-ab88-406878261ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc60e39a-c64d-4d98-a361-1641f7e8cf3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e7197bf-cd91-43bb-9056-c492279214b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JioFiber</value>
      <webElementGuid>7f710f83-d2b2-47cb-97e1-c648238d3ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstlevel-nav&quot;)/ul[1]/li[@class=&quot;cursor-pointer&quot;]/section[@class=&quot;j-container&quot;]/a[@class=&quot;j-link j-text-body-s-bold  is-text header_item-links_link&quot;]</value>
      <webElementGuid>a691a8bc-1550-45cd-892d-4be90372d040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;gotoURLGeneric('','No');trackGenericGA('Click','JioFiber','New top header','revamped_jiocom')&quot;]</value>
      <webElementGuid>3cf7ce45-9d00-4487-893c-95b7f815f377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='firstlevel-nav']/ul/li[3]/section/a</value>
      <webElementGuid>3ff71cdb-d7cf-4329-aaef-063c2bf3f42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JioFiber')]</value>
      <webElementGuid>b144fd50-6777-40f4-93a9-a20680749423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='True 5G'])[1]/following::a[1]</value>
      <webElementGuid>7c54943b-83ab-4e15-bf13-eee838f99e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/following::a[2]</value>
      <webElementGuid>eb0d4c94-03dd-4106-981e-8bfc422dd3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/preceding::a[1]</value>
      <webElementGuid>cea40a22-ac34-4764-bd4d-c2ddbce97164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[1]/preceding::a[2]</value>
      <webElementGuid>08dfe61e-61d9-4245-8171-0063333bab80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JioFiber']/parent::*</value>
      <webElementGuid>1f1c2161-482b-4650-90ac-7e05361214b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/fiber.html')]</value>
      <webElementGuid>5db177b8-722b-4d11-acf6-8b96cec777b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/section/a</value>
      <webElementGuid>74668db8-2ff0-4c58-affb-819b07c4be6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/fiber.html' and (text() = 'JioFiber' or . = 'JioFiber')]</value>
      <webElementGuid>91e78b59-0c37-4f54-acea-84af5366f947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
