<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_About_q</name>
   <tag></tag>
   <elementGuidId>abe125f2-0032-4649-8e16-b25291a8412c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchinput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchinput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9bfe2a9-16c2-4180-9e17-14b7a7b0371e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>e228b890-f5b0-4e26-87af-a4be34703ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93f023dd-9821-4957-9cc0-498dd2738543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Doodles</value>
      <webElementGuid>dde6947c-56ff-4f61-a73e-87a98aaff7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maximize</value>
      <webElementGuid>ae5791f4-1964-4a1e-b1b7-61bba8552afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchinput</value>
      <webElementGuid>f39889b2-6b8b-4d72-a984-9c55df37b702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchinput&quot;)</value>
      <webElementGuid>23896695-faba-41e9-86e7-32ac498280c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchinput']</value>
      <webElementGuid>a9280367-6108-4736-bf50-6e3879b3ecc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchform']/div/input</value>
      <webElementGuid>1e39c0d5-b023-4384-a735-db8935258d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5ebb2bf6-099d-46fa-9326-765afb502a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'q' and @type = 'text' and @placeholder = 'Search Doodles' and @id = 'searchinput']</value>
      <webElementGuid>9a9e32e3-1e7a-4cc1-a737-2da8c13b39af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
